CI (macos): Bump Python versions in workaround for Homebrew.
Homebrew's Python still conflicts with the Python that is installed by GitHub
on their macOS images.
Since recently, the `python@3.12` bottle pulls in a dependency (`openssl@3`)
that does not install on the macos-15 runner image because of a conflict:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/openssl
Target /opt/homebrew/bin/openssl
is a symlink belonging to openssl@1.1. You can unlink it:
  brew unlink openssl@1.1
```

The same conflict occurs for the `python@3.13` bottle.

Forcefully override that conflicting symlink.

Additionally, nothing we need from Homebrew still depends on the `python@3.12`
or `python@3.13` bottle any more. So, update the workaround to a newer Python
bottle.